export const ALLOWED_TOOLS = [
  'FETCH_PAGE',
  'EXTRACT_PRODUCT_JSON',
  'CHECK_VARIANT_AVAILABILITY',
  'COMPUTE_CONFIDENCE',
  'DEDUPE_ALERT',
  'SELECT_ALTERNATIVES',
  'DRAFT_EMAIL',
  'SEND_EMAIL',
  'UPDATE_INTENT_PROFILE',
  'SCHEDULE_NEXT_CHECK'
] as const;

export type AllowedTool = (typeof ALLOWED_TOOLS)[number];
